import React from 'react';
import { Audio, Sequence, staticFile, useVideoConfig, interpolate } from 'remotion';

interface MusicEvent {
  type: string;
  asset_id: string;
  start_sec: number;
  duration_sec: number;
  src: string;
  duck_dialogue?: boolean;
  duck_db?: number;
}

interface MusicTimeline {
  episode: string;
  events: MusicEvent[];
  mix_rules: {
    intro_duck_db: number;
    sting_gain_db: number;
  };
}

/**
 * EpisodeMusic — branded intro, chapter transitions, and outro stings.
 * 
 * Reads src/data/<ep>/music_timeline.json (generated by stage_music.py).
 * - Intro sting at t=0, dialogue ducks under the tail
 * - Chapter sting at each act boundary
 * - Outro sting over final seconds
 * 
 * Assets come from --music-dir if provided, else procedural audio_brand fallback.
 * Renders nothing if music_timeline.json has disabled: true.
 */
export const EpisodeMusic: React.FC<{ episode: string }> = ({ episode }) => {
  const { fps } = useVideoConfig();
  const epLower = episode.toLowerCase();
  
  let timeline: MusicTimeline | null = null;
  let disabled = false;
  
  try {
    // Dynamic import based on episode
    // Note: Remotion requires static imports, so we use a lookup
    const timelines: Record<string, any> = {
      e1: require(`../data/e1/music_timeline.json`),
      e2: require(`../data/u1e2/music_timeline.json`),
      e3: require(`../data/e3/music_timeline.json`),
      e4: require(`../data/e4/music_timeline.json`),
      e5: require(`../data/e5/music_timeline.json`),
      e6: require(`../data/e6/music_timeline.json`),
      e7: require(`../data/e7/music_timeline.json`),
      e8: require(`../data/e8/music_timeline.json`),
      e9: require(`../data/e9/music_timeline.json`),
    };
    const data = timelines[epLower];
    if (data?.disabled) {
      disabled = true;
    } else {
      timeline = data as MusicTimeline;
    }
  } catch {
    // No music timeline yet — render nothing
    return null;
  }
  
  if (disabled || !timeline) {
    return null;
  }
  
  return (
    <>
      {timeline.events.map((event, i) => {
        const startFrame = Math.floor(event.start_sec * fps);
        const durationFrames = Math.floor(event.duration_sec * fps);
        
        // Volume envelope: stings sit slightly above dialogue (-6dB = ~0.5 volume)
        // Intro ducks dialogue under tail via the event's duck_db
        const baseVolume = 0.5;
        
        return (
          <Sequence
            key={`music-${event.type}-${i}`}
            from={startFrame}
            durationInFrames={durationFrames}
          >
            <Audio
              src={staticFile(event.src)}
              volume={(frame) => {
                // Fade in/out at edges
                const fadeFrames = Math.floor(fps * 0.5);
                if (frame < fadeFrames) {
                  return interpolate(frame, [0, fadeFrames], [0, baseVolume]);
                }
                if (frame > durationFrames - fadeFrames) {
                  return interpolate(
                    frame,
                    [durationFrames - fadeFrames, durationFrames],
                    [baseVolume, 0]
                  );
                }
                return baseVolume;
              }}
            />
          </Sequence>
        );
      })}
    </>
  );
};
