"""
Measure real glyph advance widths of the bundled woff2 fonts (public/fonts) and write
src/motion/fontMetrics.ts, the table src/motion/measure.ts estimates text widths from.

  /tmp/imgvenv/bin/python tools/calibrate-fonts.py      (any Python with Pillow + FreeType/brotli)

Widths are per 1000 em (font size 1000). Glyphs a face lacks (arrows etc.) are left out, so
the estimate falls back to the face's widest-glyph factor for them (conservative).
"""
import json
import os
from PIL import ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONTS = os.path.join(ROOT, 'public', 'fonts')
OUT = os.path.join(ROOT, 'src', 'motion', 'fontMetrics.ts')

FACES = [
    ('Cinzel', 400, 'normal', 'cinzel-400-normal.woff2'),
    ('Cinzel', 700, 'normal', 'cinzel-700-normal.woff2'),
    ('Libre Baskerville', 400, 'normal', 'libre-baskerville-400-normal.woff2'),
    ('Libre Baskerville', 700, 'normal', 'libre-baskerville-700-normal.woff2'),
    ('Libre Baskerville', 400, 'italic', 'libre-baskerville-400-italic.woff2'),
    ('Plus Jakarta Sans', 400, 'normal', 'plus-jakarta-sans-400-normal.woff2'),
    ('Plus Jakarta Sans', 700, 'normal', 'plus-jakarta-sans-700-normal.woff2'),
    ('JetBrains Mono', 400, 'normal', 'jetbrains-mono-400-normal.woff2'),
    ('JetBrains Mono', 700, 'normal', 'jetbrains-mono-700-normal.woff2'),
]

LOWER = 'abcdefghijklmnopqrstuvwxyz'
UPPER = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
DIGITS = '0123456789'
CHARS = ''.join(chr(c) for c in range(32, 127)) + '’‘“”–—·…°′″éíáóúñÉ×≈£§½⇄→←'


def has_glyph(font, ch):
    """A glyph exists if it renders differently from a codepoint no font maps (U+FFFF)."""
    if ch == ' ':
        return True
    a = font.getmask(ch)
    b = font.getmask('￿')
    return not (a.size == b.size and bytes(a) == bytes(b) and font.getlength(ch) == font.getlength('￿'))


def face_metrics(path):
    f = ImageFont.truetype(path, 1000)
    widths = {}
    for ch in CHARS:
        if has_glyph(f, ch):
            widths[ch] = round(f.getlength(ch), 1)
    avg = lambda s: round(sum(widths[c] for c in s) / len(s), 1)
    mx = lambda s: round(max(widths[c] for c in s), 1)
    return {
        'widths': widths,
        'avgLower': avg(LOWER), 'maxLower': mx(LOWER),
        'avgUpper': avg(UPPER), 'maxUpper': mx(UPPER),
        'avgDigit': avg(DIGITS), 'maxDigit': mx(DIGITS),
        'space': widths[' '],
    }


out = {}
for family, weight, style, file in FACES:
    out[f'{family}|{weight}|{style}'] = face_metrics(os.path.join(FONTS, file))

with open(OUT, 'w') as fh:
    fh.write('/**\n * GENERATED by tools/calibrate-fonts.py from the woff2 files in public/fonts — do not edit.\n')
    fh.write(' * Glyph advance widths per 1000 em, plus per-face average/max factors for lowercase,\n')
    fh.write(' * capitals and digits. Key = "family|weight|style". Used by src/motion/measure.ts.\n */\n')
    fh.write('export interface FaceMetrics { widths: Record<string, number>; avgLower: number; maxLower: number; avgUpper: number; maxUpper: number; avgDigit: number; maxDigit: number; space: number }\n\n')
    fh.write('export const FONT_METRICS: Record<string, FaceMetrics> = ')
    fh.write(json.dumps(out, ensure_ascii=False, indent=1))
    fh.write(';\n')
print('wrote', OUT)
for k, v in out.items():
    print(f"{k:32s} lower avg {v['avgLower']:6.1f} max {v['maxLower']:6.1f}  caps avg {v['avgUpper']:6.1f} max {v['maxUpper']:6.1f}  glyphs {len(v['widths'])}")
