/**
 * The one text-measuring module. Every layout that needs a text width (card/pill wrapping,
 * label boxes, panel sizes, validators) measures here, so node tools and the browser agree.
 *
 * - estimateWidth: calibrated per font FACE from the real glyph advances of the bundled woff2
 *   fonts (src/motion/fontMetrics.ts, generated by tools/calibrate-fonts.py). Works without a
 *   DOM (node tests, validators, server render). Glyphs a face lacks fall back to the face's
 *   widest glyph of the same class, and the total carries a small safety margin (kerning and
 *   rounding never make real text wider than the estimate by more than a pixel or two).
 * - measureLine: in the browser @remotion/layout-utils measureText, but never less than the
 *   estimate (the first frame can render while the self-hosted fonts are still loading, and
 *   measureText caches); in node, the estimate.
 * - wrapText / fitLines: greedy wrapping and size fitting on top of either.
 */
import { measureText } from '@remotion/layout-utils';
import { FONT } from '../theme/tokens';
import { FONT_METRICS, type FaceMetrics } from './fontMetrics';

export interface Font { size: number; family: string; weight?: number; letterSpacing?: number; italic?: boolean }
export type Measure = (text: string, f: Font) => number;

/** Safety margin on estimates (kerning pairs, sub-pixel rounding). */
const MARGIN = 1.03;

/** First family name of a CSS font stack: "'Cinzel', 'Libre Baskerville', serif" → "Cinzel". */
export const primaryFamily = (stack: string) => stack.split(',')[0].trim().replace(/^['"]|['"]$/g, '');

/** Fonts that are not bundled (FONT.hand → system script fonts): measured as Libre Baskerville × this. */
const UNBUNDLED_SCALE = 1.12;

/** The calibrated face for a font (nearest bundled weight; italic if bundled). */
export function faceOf(f: Pick<Font, 'family' | 'weight' | 'italic'>): { m: FaceMetrics; scale: number } {
  let fam = primaryFamily(f.family);
  let scale = 1;
  const known = (name: string) => Object.keys(FONT_METRICS).some(k => k.startsWith(`${name}|`));
  if (!known(fam)) { fam = primaryFamily(FONT.text); scale = UNBUNDLED_SCALE; }
  const w = (f.weight ?? 400) >= 600 ? 700 : 400;
  const pick = (weight: number, style: string) => FONT_METRICS[`${fam}|${weight}|${style}`];
  const m = (f.italic ? pick(w, 'italic') ?? pick(400, 'italic') : undefined) ?? pick(w, 'normal') ?? pick(400, 'normal') ?? pick(700, 'normal');
  return { m, scale };
}

/** Per-character fallback for glyphs the face lacks (browser substitutes another font). */
function fallbackWidth(c: string, m: FaceMetrics): number {
  if (/[a-z]/.test(c)) return m.maxLower;
  if (/[0-9]/.test(c)) return m.maxDigit;
  return m.maxUpper;
}

/** Calibrated width estimate in px (no DOM needed). */
export function estimateWidth(text: string, f: Font): number {
  const { m, scale } = faceOf(f);
  let em = 0;
  let n = 0;
  for (const c of text) { em += m.widths[c] ?? fallbackWidth(c, m); n++; }
  return (em / 1000) * f.size * scale * MARGIN + n * (f.letterSpacing ?? 0);
}

/** Width used for layout: max(browser measureText, estimate); the estimate alone without a DOM. */
export function measureLine(text: string, f: Font): number {
  const est = estimateWidth(text, f);
  if (typeof document === 'undefined') return est;
  const real = measureText({
    text, fontFamily: f.family, fontSize: f.size, fontWeight: f.weight ?? 400,
    letterSpacing: f.letterSpacing ? `${f.letterSpacing}px` : undefined,
    additionalStyles: f.italic ? { fontStyle: 'italic' } : undefined,
  }).width;
  return Math.max(real, est);
}

/** Greedy word wrap at maxW. A single word wider than maxW gets its own (over-wide) line. */
export function wrapText(text: string, maxW: number, f: Font, measure: Measure = measureLine): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let cur = '';
  for (const w of words) {
    const next = cur ? `${cur} ${w}` : w;
    if (!cur || measure(next, f) <= maxW) cur = next;
    else { lines.push(cur); cur = w; }
  }
  if (cur) lines.push(cur);
  return lines;
}

/** Largest size from `sizes` (descending) whose wrap fits in maxLines with no over-wide word. */
export function fitLines(text: string, maxW: number, sizes: number[], maxLines: number, f: Omit<Font, 'size'>, measure: Measure = measureLine) {
  for (const size of sizes) {
    const font = { ...f, size };
    const greedy = wrapText(text, maxW, font, measure);
    if (greedy.length > maxLines || Math.max(...greedy.map(l => measure(l, font))) > maxW) continue;
    // balance: the narrowest width that still needs no more lines (no ragged last word)
    let lo = 0;
    let hi = maxW;
    while (hi - lo > 1) {
      const mid = (lo + hi) / 2;
      const w = wrapText(text, mid, font, measure);
      if (w.length <= greedy.length && Math.max(...w.map(l => measure(l, font))) <= mid) hi = mid; else lo = mid;
    }
    const lines = wrapText(text, hi, font, measure);
    return { size, lines, width: Math.max(...lines.map(l => measure(l, font))), fits: true };
  }
  const size = sizes[sizes.length - 1];
  const font = { ...f, size };
  const lines = wrapText(text, maxW, font, measure);
  return { size, lines, width: Math.max(...lines.map(l => measure(l, font))), fits: false };
}

/** Box of a wrapped text block: lines, width (widest line) and height (lines × lineHeight). */
export function textBlock(text: string, maxW: number, f: Font, lineHeight = 1.3, measure: Measure = estimateWidth) {
  const lines = wrapText(text, maxW, f, measure);
  return { lines, w: Math.max(0, ...lines.map(l => measure(l, f))), h: lines.length * f.size * lineHeight };
}
