import React from 'react';
import { Audio, Sequence, staticFile, useVideoConfig, interpolate } from 'remotion';

interface MusicEvent {
  type: string;
  asset_id: string;
  start_sec: number;
  duration_sec: number;
  src: string;
  duck_dialogue?: boolean;
  duck_db?: number;
}

interface MusicTimeline {
  episode: string;
  events: MusicEvent[];
  mix_rules: {
    intro_duck_db: number;
    sting_gain_db: number;
  };
}

/**
 * EpisodeMusic — branded intro, chapter transitions, and outro stings.
 * 
 * Reads src/data/<ep>/music_timeline.json (generated by stage_music.py).
 * - Intro sting at t=0, dialogue ducks under the tail
 * - Chapter sting at each act boundary
 * - Outro sting over final seconds
 * 
 * Assets come from --music-dir if provided, else procedural audio_brand fallback.
 * Renders nothing if music_timeline.json has disabled: true.
 */
export const EpisodeMusic: React.FC<{ episode: string }> = ({ episode }) => {
  const { fps } = useVideoConfig();
  const epLower = episode.toLowerCase();
  
  let timeline: MusicTimeline | null = null;
  let disabled = false;
  
  // out/data is canonical (pipeline output); src/data is the transition fallback.
  const loadTimeline = (outDir: string, srcDir: string): any | null => {
    try {
      return require(`../../out/data/${outDir}/music_timeline.json`);
    } catch {
      try {
        return require(`../data/${srcDir}/music_timeline.json`);
      } catch {
        return null;
      }
    }
  };
  const DIRS: Record<string, [string, string]> = {
    e1: ['e1', ''], e2: ['e2', 'u1e2'], e3: ['e3', 'e3'], e4: ['e4', 'e4'],
    e5: ['e5', 'e5'], e6: ['e6', 'e6'], e7: ['e7', 'e7'], e8: ['e8', 'e8'],
    e9: ['e9', 'e9'],
  };
  try {
    const dirs = DIRS[epLower];
    const data = dirs ? loadTimeline(dirs[0], dirs[1]) : null;
    if (data?.disabled) {
      disabled = true;
    } else {
      timeline = data as MusicTimeline;
    }
  } catch {
    // No music timeline yet — render nothing
    return null;
  }
  
  if (disabled || !timeline) {
    return null;
  }
  
  return (
    <>
      {timeline.events.map((event, i) => {
        const startFrame = Math.floor(event.start_sec * fps);
        const durationFrames = Math.floor(event.duration_sec * fps);
        
        // Volume envelope: stings sit slightly above dialogue (-6dB = ~0.5 volume)
        // Intro ducks dialogue under tail via the event's duck_db
        const baseVolume = 0.5;
        
        return (
          <Sequence
            key={`music-${event.type}-${i}`}
            from={startFrame}
            durationInFrames={durationFrames}
          >
            <Audio
              src={staticFile(event.src)}
              volume={(frame) => {
                // Fade in/out at edges
                const fadeFrames = Math.floor(fps * 0.5);
                if (frame < fadeFrames) {
                  return interpolate(frame, [0, fadeFrames], [0, baseVolume]);
                }
                if (frame > durationFrames - fadeFrames) {
                  return interpolate(
                    frame,
                    [durationFrames - fadeFrames, durationFrames],
                    [baseVolume, 0]
                  );
                }
                return baseVolume;
              }}
            />
          </Sequence>
        );
      })}
    </>
  );
};
