/**
 * U1E3 — "The Exchange" (Columbian Exchange).
 *
 * Kit-level rebuild. Beats are the kit's u1e3.ts spec (78 beats) resolved
 * against our v9 turns — see src/data/e3/beats_kit.json (generated by
 * /tmp/map_beats.py; every anchor verified against turns.json).
 *
 * Rendering: EpisodeShell owns boilerplate (turns, audio, heads, tone, guard);
 * beats render through the ported kit components (KitComponents/KitOverlays/
 * KitMedia); lesson-plan sections drive backgrounds and tone; our TalkingHead
 * style is kept.
 */
import React from 'react';
import { Sequence } from 'remotion';
import { EpisodeShell, ShellContext } from './EpisodeShell';
import { TitleCard } from './TitleCard';
import { SpeechBubble } from './SpeechBubble';
import { VersusPolarization } from './VersusPolarization';
import {
  PauseCard,
  RevealCard,
  BoxTracker,
  Pictogram,
  ExchangeLedger,
  RenderConfig,
} from './KitComponents';
import {
  TrapCard,
  ChapterBanner,
  QuestionCard,
  RouteMap,
  RecapBoard,
} from './KitOverlays';
import {
  DocumentView,
  TourView,
  FigureCard,
  KineticText,
} from './KitMedia';
import { SceneTone } from '../validation/ToneContext';
import { resolveAnchor, ResolveContext } from '../lib/anchors';
import { u1e3Plan } from '../data/u1e3-plan';
import beatsJson from '../data/e3/beats_kit.json';
import rcJson from '../data/render-config.json';
import placesJson from '../data/places.json';
import { loadEpisodeData } from '../lib/load-episode-data';
import { Track } from '../lib/guard';
import { KitLayer, KIT_W, KIT_H } from './KitLayer';
import { useImageAspect } from '../lib/useImageAspect';

interface Turn { id: string; speaker: string; text: string }

interface ResolvedBeat {
  id: string;
  kind: string;
  turn_id: string;
  turn_idx: number;
  offset: number;
  /** baked times from the mapping script — NOT used for timing (they drift when the pipeline re-times) */
  start: number;
  end: number;
  /** where the beat ends, as (turn, offset): re-resolved against live timing */
  end_turn_id?: string;
  end_offset?: number;
  props: Record<string, any>;
}
const rawBeats = beatsJson as ResolvedBeat[];

/** Text-like beats never sit on screen longer than this (v9 turns run up to 30s). */
const MAX_TEXT_HOLD_SEC = 9;
const TEXT_LIKE = new Set(['text', 'bubble', 'figure']);
const MAX_ROUTE_HOLD_SEC = 10;
/** Stage components fill the stage; two can't share it, and text can't sit on top of one. */
const STAGE = new Set(['route', 'tour', 'document', 'board', 'question', 'versus', 'ledger', 'pictogram', 'range']);

/**
 * Self-correcting pass over resolved beats (logged): stage components end when the next one
 * starts; nothing stays under an (exclusive) countdown card; text that would sit on a stage
 * component is dropped. Figure cards are lower-left and coexist with text.
 */
function resolveConflicts<B extends { id: string; kind: string; start: number; end: number; turn_id: string }>(
  beats: B[],
  exclusive: { start: number; end: number; id: string }[],
): { beats: B[]; fixes: string[] } {
  const fixes: string[] = [];
  const out = beats.map((b) => ({ ...b }));
  const stage = out.filter((b) => STAGE.has(b.kind)).sort((a, b) => a.start - b.start);
  for (let i = 0; i + 1 < stage.length; i++) {
    if (stage[i].end > stage[i + 1].start) {
      fixes.push(`${stage[i].id}: ends at ${stage[i + 1].start.toFixed(1)}s (was ${stage[i].end.toFixed(1)}s) so ${stage[i + 1].id} has the stage`);
      stage[i].end = stage[i + 1].start;
    }
  }
  for (const b of out) {
    if (b.kind === 'bg') continue;
    for (const x of exclusive) {
      if (b.start < x.start && b.end > x.start) {
        fixes.push(`${b.id}: ends at ${x.start.toFixed(1)}s for ${x.id}`);
        b.end = x.start;
      }
    }
  }
  // text vs stage: a stage component that overstays into a LATER turn yields to that turn's
  // text (after ≥3s of its own); text colliding on the stage component's own turn is dropped
  for (const b of out) {
    if (!TEXT_LIKE.has(b.kind) || b.kind === 'figure') continue;
    for (const st of stage) {
      const overlap = b.start < st.end - 0.05 && st.start < b.end - 0.05;
      if (overlap && b.turn_id !== st.turn_id && b.start - st.start >= 3) {
        fixes.push(`${st.id}: ends at ${b.start.toFixed(1)}s (was ${st.end.toFixed(1)}s) so ${b.id} can show`);
        st.end = b.start;
      }
    }
  }
  const kept = out.filter((b) => {
    if (!TEXT_LIKE.has(b.kind) || b.kind === 'figure') return true;
    const on = stage.find((st) => b.start < st.end - 0.05 && st.start < b.end - 0.05);
    if (on) fixes.push(`${b.id}: dropped (would sit on ${on.id} in the same turn)`);
    return !on && b.end - b.start >= 1;
  });
  return { beats: kept.filter((b) => b.end > b.start), fixes };
}

/** Kinds rendered by our own 720p components (outside the 1080p kit layer). */
const NATIVE = new Set(['bubble', 'versus']);

/* ------------------------------ render config ------------------------------ */

const CFG = {
  // kit components render inside <KitLayer> (1920×1080 scaled to the frame)
  width: KIT_W,
  height: KIT_H,
  fps: rcJson.fps,
  safe: rcJson.safe,
  stage: rcJson.stage,
  boxTracker: rcJson.boxTracker,
  captions: rcJson.captions,
  credit: rcJson.credit,
  figureCard: rcJson.figureCard,
  trapCard: rcJson.trapCard,
  ribbon: rcJson.ribbon,
  topBand: rcJson.topBand,
  reveal: rcJson.reveal,
  text: rcJson.text,
  overlayTiming: rcJson.overlayTiming ?? { termChipSec: 3, chapterBannerSec: 4, trapFactDelaySec: 2.5, yearHighlightSec: 2 },
  head: { rect: (rcJson.head.rect as unknown as [number, number, number, number]) },
  sfx: { hit: '', check: '', whoosh: '', tick: '', volume: {} },
  tones: {
    playful: { bgOpacity: 0.85, saturate: 1.1, kenBurns: 'drift' as const },
    serious: { bgOpacity: 0.9, saturate: 0.9, kenBurns: 'push' as const },
    sobering: { bgOpacity: 0.95, saturate: 0.7, kenBurns: 'push' as const },
    recap: { bgOpacity: 0.8, saturate: 1.0, kenBurns: 'drift' as const },
  },
} as unknown as RenderConfig;

/* ------------------------------ plan resolution ---------------------------- */

const planToneToScene: Record<string, SceneTone> = {
  playful: 'playful',
  serious: 'serious',
  sobering: 'dramatic',
  recap: 'fun',
};

const BOXES = ['Exchange inventory', 'Disease front', 'Who won / who paid', 'Labor crisis'];

/* -------------------------------- beat view --------------------------------- */


/**
 * All data-derived episode state. Computed inside the component (memoized),
 * never at module scope, so the data can come from props or the loader.
 */
export function deriveE3State(turns: Turn[], starts: number[], durations: number[]) {
  const totalSec = starts[starts.length - 1] + durations[durations.length - 1];
  const turnIdxById: Record<string, number> = {};
  turns.forEach((t, i) => { turnIdxById[t.id] = i; });

  const ACTX: ResolveContext = { turns, starts, durations, wordTimes: {} };

  const sections = u1e3Plan.sections
    .map((s) => ({
      start: resolveAnchor(s.from, ACTX).time,
      tone: planToneToScene[s.tone] ?? 'serious',
      bg: s.bg,
    }))
    .sort((a, b) => a.start - b.start);

  const sectionAt = (t: number) => {
    let cur = sections[0];
    for (const s of sections) if (t >= s.start) cur = s;
    return cur;
  };

  const turnStart = (id: string) => {
    const i = turnIdxById[id];
    if (i === undefined) throw new Error(`U1E3: beat refers to turn "${id}", which is not in turns.json (script changed?). Re-run the beat mapping.`);
    return starts[i];
  };
  /** visual end of a turn = next turn's start (holds through the gap) */
  const turnVisualEnd = (i: number) => (i + 1 < turns.length ? starts[i + 1] : totalSec);

  const beats = rawBeats.map((b) => {
    const start = turnStart(b.turn_id) + b.offset;
    let end = b.end_turn_id !== undefined && b.end_offset !== undefined
      ? turnStart(b.end_turn_id) + b.end_offset
      : start + (b.end - b.start);
    if (TEXT_LIKE.has(b.kind)) end = Math.min(end, start + MAX_TEXT_HOLD_SEC);
    if (b.kind === 'route') end = Math.min(end, start + MAX_ROUTE_HOLD_SEC);
    return { ...b, start, end };
  });

  const titleAt = resolveAnchor(u1e3Plan.title.at, ACTX).time;

  /* Backgrounds: bg beats override plan section backgrounds, per turn. */
  const bgByTurn: Record<string, string> = {};
  for (const b of rawBeats.map((x) => ({ ...x, start: turnStart(x.turn_id) + x.offset, end: x.end_turn_id ? turnStart(x.end_turn_id) + (x.end_offset ?? 0) : turnStart(x.turn_id) + x.offset + (x.end - x.start) }))) {
    if (b.kind !== 'bg') continue;
    turns.forEach((t, i) => {
      if (starts[i] >= b.start - 1e-6 && starts[i] < b.end - 1e-6) bgByTurn[t.id] = b.props.image;
    });
  }

  const backgroundForTurn = (turnId: string) =>
    bgByTurn[turnId] ?? sectionAt(turnStart(turnId)).bg;

  const toneForTurn = (turnId: string): SceneTone =>
    sectionAt(turnStart(turnId)).tone;

  /* ------------------------------ pause / reveal ----------------------------- */

  interface PauseSpec {
    card: { start: number; end: number; spec: { kind: string; prompt: string } };
    reveal: string;
    revealStart: number;
    revealEnd: number;
  }

  const pauses: PauseSpec[] = u1e3Plan.pauseCards.map((pc) => {
    const after = resolveAnchor(pc.after, ACTX);
    const pauseIdx = after.turnIdx + 1; // the [N-second pause] turn
    const start = starts[pauseIdx];
    const end = start + durations[pauseIdx];
    // the reveal sits on the ANSWER turn (the one after the pause)
    const revealStart = pauseIdx + 1 < turns.length ? starts[pauseIdx + 1] : end;
    const revealEnd = turnVisualEnd(pauseIdx + 1);
    const reveal = pc.reveal;
    return {
      card: { start, end, spec: { kind: pc.kind, prompt: pc.prompt } },
      reveal,
      revealStart,
      revealEnd,
    };
  });

  /* --------------------------------- traps ---------------------------------- */

  const traps = u1e3Plan.traps.map((t, i) => {
    const r = resolveAnchor(t.at, ACTX);
    if (t.factAt) {
      // one turn holds both: myth from its start, fact when the correction is spoken
      const f = resolveAnchor(t.factAt, ACTX);
      return {
        spec: { myth: t.myth, fact: t.fact },
        trapIdx: r.turnIdx,
        start: starts[r.turnIdx],
        factStart: f.time,
        end: turnVisualEnd(r.turnIdx),
        key: `trap-${i}`,
      };
    }
    const corrIdx = r.turnIdx + 1;
    return {
      spec: { myth: t.myth, fact: t.fact },
      trapIdx: r.turnIdx,
      start: starts[r.turnIdx],
      factStart: starts[corrIdx] + 0.4,
      end: turnVisualEnd(corrIdx),
      key: `trap-${i}`,
    };
  });

  /* -------------------------------- chapters --------------------------------- */

  const chapters = u1e3Plan.chapters.map((c, i) => {
    const r = resolveAnchor(c.at, ACTX);
    const nextStart = i + 1 < u1e3Plan.chapters.length
      ? resolveAnchor(u1e3Plan.chapters[i + 1].at, ACTX).time
      : totalSec;
    return {
      spec: { label: c.label, box: c.box },
      start: r.time,
      end: nextStart,
      bannerEnd: r.time + CFG.overlayTiming.chapterBannerSec,
      key: `chapter-${i}`,
    };
  });

  // Box 1 is checked mid-episode ("Checking that one."); boxes 2–4 in the recap.
  const CHECK_ANCHORS = [
    { turn: 'Checking that one.' },
    { turn: 'Box two, checked' },
    { turn: 'Box three, checked' },
    { turn: 'Box four, checked' },
  ];
  const checkedAt: (number | null)[] = CHECK_ANCHORS.map((a) => {
    try { return resolveAnchor(a, ACTX).time; } catch { return null; }
  });
  // Each row appears when Maya names that box in the cold open.
  const BOX_WORDS = ['exchange inventory', 'disease front', 'who won and who paid', 'labor crisis'];
  const introAt: (number | null)[] = BOX_WORDS.map((w) => {
    try { return resolveAnchor({ turn: 'Four boxes: the Exchange inventory', word: w }, ACTX).time; } catch { return null; }
  });

  const boxChapters = chapters.filter((c) => c.spec.box);
  const currentBoxAt = (t: number) => {
    for (const c of boxChapters) {
      if (t >= c.start && t < c.end && c.spec.box) {
        return { box: c.spec.box, progress: (t - c.start) / (c.end - c.start), since: t - c.start };
      }
    }
    return null;
  };

  const renderBeat = (b: ResolvedBeat): React.ReactNode => {
    const p = b.props;
    switch (b.kind) {
      case 'text': {
        const words = (p.text as string).split(/\s+/).filter(Boolean);
        return (
          <KineticText
            text={p.text}
            level={p.level}
            position={p.position}
            color={p.color ?? '#f5e6c8'}
            wordOffsets={words.map((_, i) => i * 0.14)}
            entrance={p.entrance ?? 'fade'}
            keywords={new Set<string>()}
            cfg={CFG}
          />
        );
      }
      case 'bubble':
        return <SpeechBubble text={p.text} position={p.position} width={p.width} />;
      case 'tour':
        return (
          <AspectTour
            beat={{
              image: p.image,
              caption: p.caption,
              stops: p.stops.map((s: { rect: [number, number, number, number]; callouts: { point: [number, number]; label: string }[] }) => ({
                rect: s.rect,
                callouts: s.callouts ?? [],
              })),
              itemOffsets: p.stops.map((s: { time: number }) => Math.max(0, s.time - b.start)),
            }}
            cfg={CFG}
          />
        );
      case 'figure':
        return (
          <FigureCard
            beat={{ name: p.name, dates: p.dates, role: p.role, likeness: p.likeness, image: p.image }}
            cfg={CFG}
          />
        );
      case 'document': {
        const words = (p.excerpt as string).split(/\s+/).filter(Boolean);
        return (
          <AspectDocument
            beat={{
              title: p.title,
              attribution: p.attribution,
              excerpt: p.excerpt,
              quoteStatus: p.quoteStatus,
              highlight: p.highlight,
              image: p.image,
              marks: p.marks,
              hipp: p.hipp,
            }}
            wordOffsets={words.map((_, i) => 0.8 + i * 0.3)}
            cfg={CFG}
          />
        );
      }
      case 'route':
        return (
          <RouteMap
            beat={{ routes: p.routes, caption: p.caption, variant: p.variant }}
            places={placesJson as unknown as Record<string, [number, number]>}
            cfg={CFG}
          />
        );
      case 'versus':
        return (
          <VersusPolarization
            clashTitle={p.clashTitle}
            periodLabel={p.periodLabel}
            entityA={p.entityA}
            entityB={p.entityB}
            verdictSummary={p.verdictSummary}
          />
        );
      case 'pictogram':
        return (
          <Pictogram
            beat={{ total: p.total, lost: p.lost, label: p.label, caption: p.caption }}
            cfg={CFG}
          />
        );
      case 'ledger':
        return (
          <ExchangeLedger
            beat={{ west: p.west, east: p.east, exception: p.exception }}
            cfg={CFG}
          />
        );
      case 'board': {
        const items = p.items.map((it: { box: number; text: string }) => ({ box: it.box, text: it.text }));
        const itemOffsets = p.items.map((it: { turn_id: string; offset: number }) =>
          Math.max(0, turnStart(it.turn_id) + it.offset - b.start));
        const footerOffset = Math.max(0, turnStart(p.footer.turn_id) + p.footer.offset - b.start);
        return (
          <RecapBoard
            beat={{ items, footer: { text: p.footer.text }, itemOffsets, footerOffset }}
            boxes={BOXES}
            checkedAt={(box: number) => checkedAt[box - 1]}
            beatStart={b.start}
            cfg={CFG}
          />
        );
      }
      case 'question':
        return (
          <QuestionCard
            beat={{ number: p.number, format: p.format, stem: p.stem, source: p.source }}
            cfg={CFG}
          />
        );
      default:
        return null;
    }
  };

  const resolved = resolveConflicts(beats, pauses.map((p, i) => ({ start: p.card.start, end: p.card.end, id: `pause card ${i}` })));
  if (resolved.fixes.length) console.info(`[U1E3] ${resolved.fixes.length} automatic timing fixes:\n  ` + resolved.fixes.join('\n  '));

  return {
    turns, starts, durations, beats: resolved.beats, layoutFixes: resolved.fixes,
    titleAt, backgroundForTurn, toneForTurn,
    pauses, traps, chapters,
    checkedAt, introAt, currentBoxAt,
    renderBeat,
  };
}

/* ------------------------- aspect-aware media wrappers ------------------------- */

/** Tour/document with the image's REAL aspect (hard-coded aspects squashed scans and moved marks). */
const AspectTour: React.FC<Omit<React.ComponentProps<typeof TourView>, 'imageAspect' | 'regionRect'>> = (props) => {
  const aspect = useImageAspect(props.beat.image, 16 / 9);
  return <TourView {...props} imageAspect={aspect} regionRect={() => undefined} />;
};
const AspectDocument: React.FC<Omit<React.ComponentProps<typeof DocumentView>, 'imageAspect'>> = (props) => {
  const aspect = useImageAspect(props.beat.image, 4 / 3);
  return <DocumentView {...props} imageAspect={aspect} />;
};

/* --------------------------------- episode ---------------------------------- */

/** One beat: timed Sequence → its own guard Track → kit layer (1080p) unless native. */
const timed = (key: string, start: number, end: number, fps: number, el: React.ReactNode, opts: { role?: 'text' | 'stage' | 'overlay' | 'cover'; native?: boolean } = {}) => (
  <Sequence key={key} from={Math.round(start * fps)} durationInFrames={Math.max(1, Math.round((end - start) * fps))} layout="none" name={key}>
    <Track id={key} role={opts.role ?? 'stage'}>
      {opts.native ? el : <KitLayer>{el}</KitLayer>}
    </Track>
  </Sequence>
);

export const U1E3Episode: React.FC = () => {
  const s = React.useMemo(() => {
    const d = loadEpisodeData('e3'); // out/data/e3 first, then src/data/e3
    if (!d.turns.length) throw new Error('U1E3: no turns/timing found (out/data/e3 or src/data/e3). Run the pipeline.');
    return deriveE3State(d.turns, d.starts, d.durations);
  }, []);
  return (
  <EpisodeShell
    episode="E3"
    turns={s.turns}
    starts={s.starts}
    durations={s.durations}
    audioPath={(id) => `audio/e3/${id}.mp3`}
    backgroundForTurn={s.backgroundForTurn}
    toneForTurn={s.toneForTurn}
    hideDefaultPauseCard
    trackChildren={false}
  >
    {(ctx: ShellContext) => {
      const fps = ctx.fps;
      return (
        <>
          {/* Title card (our 720p component) */}
          {timed('cover:title', s.titleAt, s.titleAt + (rcJson.titleCardSec ?? 3), fps, (
            <TitleCard
              at={0}
              kicker={u1e3Plan.title.kicker}
              title={u1e3Plan.title.title}
              subline={u1e3Plan.title.subline}
            />
          ), { role: 'cover', native: true })}

          {/* Beats (bg beats are handled by backgroundForTurn) */}
          {s.beats.filter((b) => b.kind !== 'bg').map((b) =>
            timed(`beat:${b.id}`, b.start, b.end, fps, s.renderBeat(b), {
              role: TEXT_LIKE.has(b.kind) ? 'text' : 'stage',
              native: NATIVE.has(b.kind),
            }),
          )}

          {/* Pause cards + reveals */}
          {s.pauses.map((pc, i) => (
            <React.Fragment key={`pause-${i}`}>
              {timed(`pause:${i}`, pc.card.start, pc.card.end, fps, <PauseCard card={pc.card} cfg={CFG} />, { role: 'overlay' })}
              {timed(`reveal:${i}`, pc.revealStart, pc.revealEnd, fps, <RevealCard text={pc.reveal} cfg={CFG} />, { role: 'overlay' })}
            </React.Fragment>
          ))}

          {/* Trap cards */}
          {s.traps.map((t) => timed(`trap:${t.key}`, t.start, t.end, fps, <TrapCard trap={t} cfg={CFG} />, { role: 'overlay' }))}

          {/* Chapter banners (box chapters only) */}
          {s.chapters.filter((c) => c.spec.box).map((c) => timed(`chapter:${c.key}`, c.start, c.bannerEnd, fps, <ChapterBanner chapter={c} cfg={CFG} />, { role: 'overlay' }))}

          {/* Episode sheet — appears as Maya names the boxes */}
          <Track id="chrome:box-tracker" role="chrome">
            <KitLayer>
              <BoxTracker
                state={{ boxes: BOXES, checkedAt: s.checkedAt, introAt: s.introAt, current: s.currentBoxAt(ctx.timeSec), t: ctx.timeSec }}
                cfg={CFG}
              />
            </KitLayer>
          </Track>
        </>
      );
    }}
  </EpisodeShell>
  );
};

/** Composition duration from live data (no bundle-time JSON import with a hard-coded path). */
export const u1e3DurationInFrames = (fps: number): number => {
  const d = loadEpisodeData('e3');
  if (!d.starts.length) return fps;
  return Math.max(fps, Math.ceil((d.starts[d.starts.length - 1] + d.durations[d.durations.length - 1]) * fps));
};
